name: Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary
          if_key_exists: replace

      - name: Add known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to Digital Ocean
        run: |
          ssh root@${{ secrets.SERVER_IP }} '
            cd /home
            git clone https://github.com/viktorholk/humidity-iot.git
            cd humidity-iot/
            docker compose down
            docker compose up -d --build
          ' 
